<?php
if (!defined('ABSPATH')) exit;

add_action('acf/init', function () {
  if (!function_exists('acf_add_local_field_group')) return;

  acf_add_local_field_group([
    'key' => 'group_moma_case_studies_archive_page',
    'title' => 'Pagina Case Studies',
    'fields' => [
      [
        'key' => 'field_csa_hero_tab',
        'label' => 'Hero',
        'type' => 'tab',
        'placement' => 'top',
      ],
      [
        'key' => 'field_csa_hero_type',
        'label' => 'Tipo contenuto hero',
        'name' => 'csa_hero_type',
        'type' => 'radio',
        'layout' => 'horizontal',
        'choices' => [
          'video' => 'Video',
          'image' => 'Immagine',
        ],
        'default_value' => 'video',
        'instructions' => 'Scegli se mostrare un video di sfondo o una singola immagine nella hero dell\'archivio Case Studies.',
      ],
      [
        'key' => 'field_csa_hero_video_webm',
        'label' => 'Video WebM (consigliato)',
        'name' => 'csa_hero_video_webm',
        'type' => 'file',
        'return_format' => 'array',
        'mime_types' => 'webm',
        'conditional_logic' => [[[
          'field' => 'field_csa_hero_type',
          'operator' => '==',
          'value' => 'video',
        ]]],
        'instructions' => 'Formato consigliato per il web. Video breve, senza audio, leggero e in loop.',
      ],
      [
        'key' => 'field_csa_hero_video_mp4',
        'label' => 'Video MP4 (fallback)',
        'name' => 'csa_hero_video_mp4',
        'type' => 'file',
        'return_format' => 'array',
        'mime_types' => 'mp4',
        'conditional_logic' => [[[
          'field' => 'field_csa_hero_type',
          'operator' => '==',
          'value' => 'video',
        ]]],
        'instructions' => 'Fallback per browser che non supportano WebM.',
      ],
      [
        'key' => 'field_csa_hero_video_poster',
        'label' => 'Poster video',
        'name' => 'csa_hero_video_poster',
        'type' => 'image',
        'return_format' => 'array',
        'preview_size' => 'large',
        'conditional_logic' => [[[
          'field' => 'field_csa_hero_type',
          'operator' => '==',
          'value' => 'video',
        ]]],
        'instructions' => 'Immagine mostrata durante il caricamento del video.',
      ],
      [
        'key' => 'field_csa_hero_image',
        'label' => 'Immagine hero',
        'name' => 'csa_hero_image',
        'type' => 'image',
        'return_format' => 'array',
        'preview_size' => 'large',
        'conditional_logic' => [[[
          'field' => 'field_csa_hero_type',
          'operator' => '==',
          'value' => 'image',
        ]]],
        'instructions' => 'Usa un\'immagine orizzontale ottimizzata, preferibilmente 1920x1080 o simile.',
      ],
      [
        'key' => 'field_csa_hero_cursor_enabled',
        'label' => 'Cursore custom hero attivo',
        'name' => 'csa_hero_cursor_enabled',
        'type' => 'true_false',
        'ui' => 1,
        'default_value' => 1,
        'instructions' => 'Mostra il cursore con immagine quando il mouse passa sopra la hero della pagina Case Studies.',
      ],
      [
        'key' => 'field_csa_hero_cursor_image',
        'label' => 'Immagine cursore hero',
        'name' => 'csa_hero_cursor_image',
        'type' => 'image',
        'return_format' => 'array',
        'preview_size' => 'medium',
        'conditional_logic' => [[[
          'field' => 'field_csa_hero_cursor_enabled',
          'operator' => '==',
          'value' => '1',
        ]]],
        'instructions' => 'Immagine usata come cursore custom sopra la hero.',
      ],
      [
        'key' => 'field_csa_statement_tab',
        'label' => 'Welcome statement',
        'type' => 'tab',
        'placement' => 'top',
      ],
      [
        'key' => 'field_csa_statement_title',
        'label' => 'Titolo statement',
        'name' => 'csa_statement_title',
        'type' => 'text',
        'default_value' => 'Welcome statement pagina progetti',
        'instructions' => 'Titolo principale della sezione introduttiva, visibile a sinistra.',
      ],
      [
        'key' => 'field_csa_statement_text',
        'label' => 'Testo statement',
        'name' => 'csa_statement_text',
        'type' => 'textarea',
        'new_lines' => 'br',
        'rows' => 4,
        'instructions' => 'Breve testo introduttivo sotto al titolo. Mantienilo sintetico.',
      ],
      [
        'key' => 'field_csa_statement_case_study',
        'label' => 'Case study in evidenza nello statement',
        'name' => 'csa_statement_case_study',
        'type' => 'relationship',
        'post_type' => ['case_study'],
        'filters' => ['search'],
        'max' => 1,
        'return_format' => 'id',
        'instructions' => 'Seleziona il case study mostrato nella card a destra della sezione introduttiva. Se lasci vuoto, verrà scelto automaticamente.',
      ],
      [
        'key' => 'field_csa_archive_tab',
        'label' => 'Archivio e filtri',
        'type' => 'tab',
        'placement' => 'top',
      ],
      [
        'key' => 'field_csa_cards_cursor_enabled',
        'label' => 'Cursore custom immagini card attivo',
        'name' => 'csa_cards_cursor_enabled',
        'type' => 'true_false',
        'ui' => 1,
        'default_value' => 1,
        'instructions' => 'Mostra il cursore con immagine solo sulle immagini delle card Case Studies, non sul resto della card.',
      ],
      [
        'key' => 'field_csa_cards_cursor_image',
        'label' => 'Immagine cursore card',
        'name' => 'csa_cards_cursor_image',
        'type' => 'image',
        'return_format' => 'array',
        'preview_size' => 'medium',
        'conditional_logic' => [[[
          'field' => 'field_csa_cards_cursor_enabled',
          'operator' => '==',
          'value' => '1',
        ]]],
        'instructions' => 'Immagine usata come cursore custom sopra le immagini delle card.',
      ],
      [
        'key' => 'field_csa_filter_all_label',
        'label' => 'Etichetta pulsante “Tutte”',
        'name' => 'csa_filter_all_label',
        'type' => 'text',
        'default_value' => 'Tutte',
        'instructions' => 'Testo del pulsante che mostra tutte le case studies.',
      ],
      [
        'key' => 'field_csa_empty_results_text',
        'label' => 'Messaggio nessun risultato',
        'name' => 'csa_empty_results_text',
        'type' => 'text',
        'default_value' => 'Nessun case study disponibile per questa categoria.',
        'instructions' => 'Messaggio mostrato quando un filtro non restituisce card visibili.',
      ],
      [
        'key' => 'field_csa_banner_tab',
        'label' => 'Banner servizi',
        'type' => 'tab',
        'placement' => 'top',
      ],
      [
        'key' => 'field_csa_banner_title',
        'label' => 'Titolo banner',
        'name' => 'csa_banner_title',
        'type' => 'text',
        'default_value' => 'Scopri i nostri servizi',
      ],
      [
        'key' => 'field_csa_banner_text',
        'label' => 'Testo banner',
        'name' => 'csa_banner_text',
        'type' => 'textarea',
        'new_lines' => 'br',
        'rows' => 3,
        'instructions' => 'Testo breve sotto al titolo del banner.',
      ],
      [
        'key' => 'field_csa_banner_btn_label',
        'label' => 'Testo pulsante',
        'name' => 'csa_banner_btn_label',
        'type' => 'text',
        'default_value' => 'vai ai servizi',
      ],
      [
        'key' => 'field_csa_banner_btn_url',
        'label' => 'Link pulsante',
        'name' => 'csa_banner_btn_url',
        'type' => 'url',
        'default_value' => home_url('/servizi'),
      ],
      [
        'key' => 'field_csa_banner_cursor_enabled',
        'label' => 'Cursore custom banner attivo',
        'name' => 'csa_banner_cursor_enabled',
        'type' => 'true_false',
        'ui' => 1,
        'default_value' => 1,
        'instructions' => 'Mostra il cursore con immagine sopra il banner servizi, escluso il pulsante.',
      ],
      [
        'key' => 'field_csa_banner_cursor_image',
        'label' => 'Immagine cursore banner',
        'name' => 'csa_banner_cursor_image',
        'type' => 'image',
        'return_format' => 'array',
        'preview_size' => 'medium',
        'conditional_logic' => [[[
          'field' => 'field_csa_banner_cursor_enabled',
          'operator' => '==',
          'value' => '1',
        ]]],
        'instructions' => 'Immagine usata come cursore custom sopra il banner servizi.',
      ],
    ],
    'location' => [[[
      'param' => 'options_page',
      'operator' => '==',
      'value' => 'moma-case-studies-page',
    ]]],
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'active' => true,
  ]);
});
