<?php
if (!defined('ABSPATH')) exit;

add_action('acf/init', function () {
  if (!function_exists('acf_add_local_field_group')) return;

  acf_add_local_field_group([
    'key' => 'group_moma_multimedia_page',
    'title' => 'Pagina Multimedia',
    'style' => 'seamless',
    'position' => 'acf_after_title',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'menu_order' => 30,
    'location' => [[[
      'param' => 'page_template',
      'operator' => '==',
      'value' => 'templates/page-multimedia.php',
    ]]],
    'fields' => [
      [
        'key' => 'field_mmp_message',
        'label' => 'Indicazioni',
        'name' => '',
        'type' => 'message',
        'message' => '<strong>Pagina Multimedia</strong><br>Questa pagina mostra automaticamente i case studies che hanno un video principale compilato. I filtri e i pulsanti categoria usano le categorie video assegnate nel blocco video del singolo case study e rimandano sempre alla stessa pagina Multimedia filtrata.',
      ],
      [
        'key' => 'field_mmp_tab_hero',
        'label' => '1. Hero',
        'type' => 'tab',
        'placement' => 'top',
      ],
      [
        'key' => 'field_mmp_hero_layout',
        'label' => 'Media hero',
        'name' => '',
        'type' => 'accordion',
        'open' => 1,
        'multi_expand' => 1,
      ],
      [
        'key' => 'field_mmp_hero_type',
        'label' => 'Tipo media hero',
        'name' => 'mmp_hero_type',
        'type' => 'button_group',
        'choices' => [
          'image' => 'Immagine',
          'video' => 'Video',
        ],
        'default_value' => 'image',
        'layout' => 'horizontal',
        'instructions' => 'Scegli se usare un’immagine statica o un video di sfondo per la hero.',
      ],
      [
        'key' => 'field_mmp_hero_image',
        'label' => 'Immagine hero',
        'name' => 'mmp_hero_image',
        'type' => 'image',
        'return_format' => 'array',
        'preview_size' => 'large',
        'conditional_logic' => [[[
          'field' => 'field_mmp_hero_type',
          'operator' => '==',
          'value' => 'image',
        ]]],
        'instructions' => 'Immagine piena larghezza usata come sfondo hero.',
      ],
      [
        'key' => 'field_mmp_hero_video_webm',
        'label' => 'Video hero WebM',
        'name' => 'mmp_hero_video_webm',
        'type' => 'file',
        'return_format' => 'array',
        'mime_types' => 'webm',
        'wrapper' => ['width' => '33'],
        'conditional_logic' => [[[
          'field' => 'field_mmp_hero_type',
          'operator' => '==',
          'value' => 'video',
        ]]],
        'instructions' => 'Formato consigliato per prestazioni migliori. Mantieni il peso più basso possibile.',
      ],
      [
        'key' => 'field_mmp_hero_video_mp4',
        'label' => 'Video hero MP4',
        'name' => 'mmp_hero_video_mp4',
        'type' => 'file',
        'return_format' => 'array',
        'mime_types' => 'mp4',
        'wrapper' => ['width' => '33'],
        'conditional_logic' => [[[
          'field' => 'field_mmp_hero_type',
          'operator' => '==',
          'value' => 'video',
        ]]],
        'instructions' => 'Fallback per browser che non gestiscono WebM.',
      ],
      [
        'key' => 'field_mmp_hero_video_poster',
        'label' => 'Poster video hero',
        'name' => 'mmp_hero_video_poster',
        'type' => 'image',
        'return_format' => 'array',
        'preview_size' => 'medium',
        'wrapper' => ['width' => '34'],
        'conditional_logic' => [[[
          'field' => 'field_mmp_hero_type',
          'operator' => '==',
          'value' => 'video',
        ]]],
        'instructions' => 'Immagine mostrata prima del caricamento del video.',
      ],
      [
        'key' => 'field_mmp_hero_cursor_enabled',
        'label' => 'Cursore custom in hero',
        'name' => 'mmp_hero_cursor_enabled',
        'type' => 'true_false',
        'ui' => 1,
        'default_value' => 1,
        'wrapper' => ['width' => '33'],
        'instructions' => 'Attiva il cursore con immagine solo sopra la hero.',
      ],
      [
        'key' => 'field_mmp_hero_cursor_image',
        'label' => 'Immagine cursore hero',
        'name' => 'mmp_hero_cursor_image',
        'type' => 'image',
        'return_format' => 'array',
        'preview_size' => 'thumbnail',
        'wrapper' => ['width' => '33'],
        'conditional_logic' => [[[
          'field' => 'field_mmp_hero_cursor_enabled',
          'operator' => '==',
          'value' => '1',
        ]]],
        'instructions' => 'Immagine mostrata dal cursore quando il mouse passa sulla hero.',
      ],
      [
        'key' => 'field_mmp_tab_intro',
        'label' => '2. Intro e griglia video',
        'type' => 'tab',
        'placement' => 'top',
      ],
      [
        'key' => 'field_mmp_intro_layout',
        'label' => 'Titolo, testo e impostazioni griglia',
        'name' => '',
        'type' => 'accordion',
        'open' => 1,
        'multi_expand' => 1,
      ],
      [
        'key' => 'field_mmp_intro_title',
        'label' => 'Titolo intro',
        'name' => 'mmp_intro_title',
        'type' => 'text',
        'default_value' => 'Welcome statement area multimediale',
        'instructions' => 'Titolo grande mostrato sotto la hero, centrato nella pagina.',
      ],
      [
        'key' => 'field_mmp_intro_text',
        'label' => 'Testo intro',
        'name' => 'mmp_intro_text',
        'type' => 'textarea',
        'rows' => 4,
        'new_lines' => 'br',
        'instructions' => 'Testo opzionale sotto il titolo. Se lasciato vuoto, non viene mostrato.',
      ],
      [
        'key' => 'field_mmp_posts_per_page',
        'label' => 'Case studies per pagina',
        'name' => 'mmp_posts_per_page',
        'type' => 'number',
        'default_value' => 6,
        'min' => 1,
        'max' => 24,
        'step' => 1,
        'wrapper' => ['width' => '33'],
        'instructions' => 'Numero di card video mostrate per pagina nella griglia.',
      ],
      [
        'key' => 'field_mmp_media_cursor_enabled',
        'label' => 'Cursore custom sulle immagini card',
        'name' => 'mmp_media_cursor_enabled',
        'type' => 'true_false',
        'ui' => 1,
        'default_value' => 1,
        'wrapper' => ['width' => '33'],
        'instructions' => 'Attiva il cursore con immagine solo sopra le immagini delle card video.',
      ],
      [
        'key' => 'field_mmp_media_cursor_image',
        'label' => 'Immagine cursore card',
        'name' => 'mmp_media_cursor_image',
        'type' => 'image',
        'return_format' => 'array',
        'preview_size' => 'thumbnail',
        'wrapper' => ['width' => '34'],
        'conditional_logic' => [[[
          'field' => 'field_mmp_media_cursor_enabled',
          'operator' => '==',
          'value' => '1',
        ]]],
        'instructions' => 'Immagine usata come cursore custom sopra le immagini delle card. Non appare sul resto della card o sui pulsanti categoria.',
      ],
      [
        'key' => 'field_mmp_tab_banner',
        'label' => '3. Banner finale',
        'type' => 'tab',
        'placement' => 'top',
      ],
      [
        'key' => 'field_mmp_banner_layout',
        'label' => 'Banner arancione',
        'name' => '',
        'type' => 'accordion',
        'open' => 1,
        'multi_expand' => 1,
      ],
      [
        'key' => 'field_mmp_banner_show',
        'label' => 'Mostra banner finale',
        'name' => 'mmp_banner_show',
        'type' => 'true_false',
        'ui' => 1,
        'default_value' => 1,
        'instructions' => 'Se attivo, sotto la griglia appare il banner arancione con pulsante.',
      ],
      [
        'key' => 'field_mmp_banner_title',
        'label' => 'Titolo banner',
        'name' => 'mmp_banner_title',
        'type' => 'text',
        'default_value' => 'Scopri i nostri lavori',
        'conditional_logic' => [[[
          'field' => 'field_mmp_banner_show',
          'operator' => '==',
          'value' => '1',
        ]]],
        'instructions' => 'Titolo principale del banner finale.',
      ],
      [
        'key' => 'field_mmp_banner_text',
        'label' => 'Testo banner',
        'name' => 'mmp_banner_text',
        'type' => 'textarea',
        'rows' => 3,
        'new_lines' => 'br',
        'conditional_logic' => [[[
          'field' => 'field_mmp_banner_show',
          'operator' => '==',
          'value' => '1',
        ]]],
        'instructions' => 'Testo breve opzionale sotto al titolo del banner.',
      ],
      [
        'key' => 'field_mmp_banner_button_label',
        'label' => 'Testo pulsante banner',
        'name' => 'mmp_banner_button_label',
        'type' => 'text',
        'default_value' => 'vai a contatti',
        'wrapper' => ['width' => '40'],
        'conditional_logic' => [[[
          'field' => 'field_mmp_banner_show',
          'operator' => '==',
          'value' => '1',
        ]]],
        'instructions' => 'Etichetta del pulsante posizionato in basso a destra nel banner.',
      ],
      [
        'key' => 'field_mmp_banner_button_url',
        'label' => 'Link pulsante banner',
        'name' => 'mmp_banner_button_url',
        'type' => 'url',
        'wrapper' => ['width' => '60'],
        'conditional_logic' => [[[
          'field' => 'field_mmp_banner_show',
          'operator' => '==',
          'value' => '1',
        ]]],
        'instructions' => 'URL completo o relativo della pagina da aprire cliccando il pulsante del banner.',
      ],
    ],
  ]);
});
