<?php
if (!defined('ABSPATH')) exit;

if (!function_exists('moma_cs_single_media_group_field')) {
  function moma_cs_single_media_group_field(string $prefix, string $label, string $name, array $args = []): array
  {
    $args = wp_parse_args($args, [
      'instructions'       => '',
      'conditional_logic'  => [],
      'layout'             => 'block',
    ]);

    return [
      'key' => $prefix . '_group',
      'label' => $label,
      'name' => $name,
      'type' => 'group',
      'layout' => $args['layout'],
      'instructions' => $args['instructions'],
      'conditional_logic' => $args['conditional_logic'],
      'sub_fields' => [
        [
          'key' => $prefix . '_media_type',
          'label' => 'Tipo contenuto',
          'name' => 'media_type',
          'type' => 'button_group',
          'choices' => [
            'image' => 'Immagine',
            'video' => 'Video',
          ],
          'default_value' => 'image',
          'layout' => 'horizontal',
          'wrapper' => ['width' => '30'],
          'instructions' => 'Scegli se visualizzare un’immagine oppure un video con miniatura e apertura in lightbox.',
        ],
        [
          'key' => $prefix . '_image',
          'label' => 'Immagine',
          'name' => 'image',
          'type' => 'image',
          'return_format' => 'array',
          'preview_size' => 'medium',
          'library' => 'all',
          'wrapper' => ['width' => '40'],
          'conditional_logic' => [[[
            'field' => $prefix . '_media_type',
            'operator' => '==',
            'value' => 'image',
          ]]],
          'instructions' => 'Carica un’immagine orizzontale ottimizzata. WordPress genererà automaticamente i ritagli utili.',
        ],
        [
          'key' => $prefix . '_enable_lightbox',
          'label' => 'Apri immagine in lightbox',
          'name' => 'enable_lightbox',
          'type' => 'true_false',
          'ui' => 1,
          'default_value' => 1,
          'wrapper' => ['width' => '30'],
          'conditional_logic' => [[[
            'field' => $prefix . '_media_type',
            'operator' => '==',
            'value' => 'image',
          ]]],
          'instructions' => 'Se attivo, il click sull’immagine apre la versione grande in lightbox.',
        ],
        [
          'key' => $prefix . '_video_source',
          'label' => 'Sorgente video',
          'name' => 'video_source',
          'type' => 'button_group',
          'choices' => [
            'upload' => 'File caricati in WordPress',
            'youtube' => 'YouTube',
            'vimeo' => 'Vimeo',
          ],
          'default_value' => 'upload',
          'layout' => 'horizontal',
          'wrapper' => ['width' => '50'],
          'conditional_logic' => [[[
            'field' => $prefix . '_media_type',
            'operator' => '==',
            'value' => 'video',
          ]]],
          'instructions' => 'Per i file caricati in WordPress, usa video brevi e leggeri. Ideale: WebM + MP4 fallback.',
        ],
        [
          'key' => $prefix . '_video_file_webm',
          'label' => 'Video WebM',
          'name' => 'video_file_webm',
          'type' => 'file',
          'return_format' => 'array',
          'mime_types' => 'webm',
          'wrapper' => ['width' => '25'],
          'conditional_logic' => [[[
            'field' => $prefix . '_media_type',
            'operator' => '==',
            'value' => 'video',
          ], [
            'field' => $prefix . '_video_source',
            'operator' => '==',
            'value' => 'upload',
          ]]],
          'instructions' => 'Formato consigliato per prestazioni migliori.',
        ],
        [
          'key' => $prefix . '_video_file_mp4',
          'label' => 'Video MP4',
          'name' => 'video_file_mp4',
          'type' => 'file',
          'return_format' => 'array',
          'mime_types' => 'mp4',
          'wrapper' => ['width' => '25'],
          'conditional_logic' => [[[
            'field' => $prefix . '_media_type',
            'operator' => '==',
            'value' => 'video',
          ], [
            'field' => $prefix . '_video_source',
            'operator' => '==',
            'value' => 'upload',
          ]]],
          'instructions' => 'Fallback per i browser che non gestiscono WebM.',
        ],
        [
          'key' => $prefix . '_video_url',
          'label' => 'URL video',
          'name' => 'video_url',
          'type' => 'url',
          'wrapper' => ['width' => '50'],
          'conditional_logic' => [[[
            'field' => $prefix . '_media_type',
            'operator' => '==',
            'value' => 'video',
          ], [
            'field' => $prefix . '_video_source',
            'operator' => '!=',
            'value' => 'upload',
          ]]],
          'instructions' => 'Inserisci l’URL completo della pagina YouTube o Vimeo del video.',
        ],
        [
          'key' => $prefix . '_video_thumbnail',
          'label' => 'Thumbnail video',
          'name' => 'video_thumbnail',
          'type' => 'image',
          'return_format' => 'array',
          'preview_size' => 'medium',
          'wrapper' => ['width' => '50'],
          'conditional_logic' => [[[
            'field' => $prefix . '_media_type',
            'operator' => '==',
            'value' => 'video',
          ]]],
          'instructions' => 'Immagine mostrata nel layout della pagina prima dell’apertura del video in lightbox.',
        ],
      ],
    ];
  }
}

if (!function_exists('moma_cs_single_video_group_field')) {
  function moma_cs_single_video_group_field(string $prefix, string $label, string $name, array $args = []): array
  {
    $args = wp_parse_args($args, [
      'instructions'      => '',
      'conditional_logic' => [],
      'layout'            => 'block',
    ]);

    return [
      'key' => $prefix . '_group',
      'label' => $label,
      'name' => $name,
      'type' => 'group',
      'layout' => $args['layout'],
      'instructions' => $args['instructions'],
      'conditional_logic' => $args['conditional_logic'],
      'sub_fields' => [
        [
          'key' => $prefix . '_video_source',
          'label' => 'Sorgente video',
          'name' => 'video_source',
          'type' => 'button_group',
          'choices' => [
            'upload' => 'File caricati in WordPress',
            'youtube' => 'YouTube',
            'vimeo' => 'Vimeo',
          ],
          'default_value' => 'upload',
          'layout' => 'horizontal',
          'wrapper' => ['width' => '50'],
          'instructions' => 'Per i file caricati, mantieni il peso il più basso possibile. Ideale: WebM + MP4 fallback.',
        ],
        [
          'key' => $prefix . '_video_file_webm',
          'label' => 'Video WebM',
          'name' => 'video_file_webm',
          'type' => 'file',
          'return_format' => 'array',
          'mime_types' => 'webm',
          'wrapper' => ['width' => '25'],
          'conditional_logic' => [[[
            'field' => $prefix . '_video_source',
            'operator' => '==',
            'value' => 'upload',
          ]]],
        ],
        [
          'key' => $prefix . '_video_file_mp4',
          'label' => 'Video MP4',
          'name' => 'video_file_mp4',
          'type' => 'file',
          'return_format' => 'array',
          'mime_types' => 'mp4',
          'wrapper' => ['width' => '25'],
          'conditional_logic' => [[[
            'field' => $prefix . '_video_source',
            'operator' => '==',
            'value' => 'upload',
          ]]],
        ],
        [
          'key' => $prefix . '_video_url',
          'label' => 'URL video',
          'name' => 'video_url',
          'type' => 'url',
          'wrapper' => ['width' => '50'],
          'conditional_logic' => [[[
            'field' => $prefix . '_video_source',
            'operator' => '!=',
            'value' => 'upload',
          ]]],
        ],
        [
          'key' => $prefix . '_video_thumbnail',
          'label' => 'Thumbnail video',
          'name' => 'video_thumbnail',
          'type' => 'image',
          'return_format' => 'array',
          'preview_size' => 'medium',
          'wrapper' => ['width' => '50'],
          'instructions' => 'Immagine mostrata nella pagina prima del click sul play.',
        ],
      ],
    ];
  }
}

add_action('acf/init', function () {
  if (!function_exists('acf_add_local_field_group')) return;

  acf_add_local_field_group([
    'key' => 'group_moma_case_study_single_fields',
    'title' => 'Case Study – Pagina dettaglio',
    'style' => 'seamless',
    'position' => 'acf_after_title',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'menu_order' => 20,
    'location' => [[[
      'param' => 'post_type',
      'operator' => '==',
      'value' => 'case_study',
    ]]],
    'fields' => [
      [
        'key' => 'field_css_intro_message',
        'label' => 'Indicazioni',
        'name' => '',
        'type' => 'message',
        'message' => '<strong>Pagina dettaglio Case Study</strong><br>Compila solo le sezioni che vuoi mostrare. Nel frontend, ogni blocco senza contenuti viene nascosto automaticamente. L’immagine in evidenza di WordPress viene usata come immagine principale del progetto nella prima sezione.',
      ],
      [
        'key' => 'field_css_tab_hero',
        'label' => '1. Hero progetto',
        'type' => 'tab',
        'placement' => 'top',
      ],
      [
        'key' => 'field_css_client_logo',
        'label' => 'Logo brand cliente',
        'name' => 'cs_client_logo',
        'type' => 'image',
        'return_format' => 'array',
        'preview_size' => 'medium',
        'library' => 'all',
        'wrapper' => ['width' => '50'],
        'instructions' => 'Logo mostrato a destra del titolo del case study.',
      ],
      [
        'key' => 'field_css_hero_enable_lightbox',
        'label' => 'Apri immagine principale in lightbox',
        'name' => 'cs_hero_enable_lightbox',
        'type' => 'true_false',
        'ui' => 1,
        'default_value' => 1,
        'wrapper' => ['width' => '50'],
        'instructions' => 'Se attivo, il click sull’immagine in evidenza apre la versione grande.',
      ],
      [
        'key' => 'field_css_tab_client',
        'label' => '2. Chi è il cliente',
        'type' => 'tab',
        'placement' => 'top',
      ],
      [
        'key' => 'field_css_client_title',
        'label' => 'Titolo sezione cliente',
        'name' => 'cs_client_title',
        'type' => 'text',
        'default_value' => 'Chi è il cliente.',
        'instructions' => 'Titolo della sezione introduttiva sotto all’immagine principale.',
      ],
      [
        'key' => 'field_css_client_text',
        'label' => 'Testo sezione cliente',
        'name' => 'cs_client_text',
        'type' => 'textarea',
        'rows' => 5,
        'new_lines' => 'br',
        'instructions' => 'Descrizione breve del cliente. Vai a capo solo dove serve davvero.',
      ],
      [
        'key' => 'field_css_tab_problem',
        'label' => '3. Problema e dato chiave',
        'type' => 'tab',
        'placement' => 'top',
      ],
      [
        'key' => 'field_css_problem_title',
        'label' => 'Titolo box sinistro',
        'name' => 'cs_problem_title',
        'type' => 'text',
        'default_value' => 'Problema del cliente.',
        'wrapper' => ['width' => '66'],
        'instructions' => 'Titolo del box grande a sinistra.',
      ],
      [
        'key' => 'field_css_metric_title',
        'label' => 'Titolo box destro',
        'name' => 'cs_metric_title',
        'type' => 'text',
        'default_value' => 'dato / performance',
        'wrapper' => ['width' => '34'],
        'instructions' => 'Titolo piccolo del box numerico a destra.',
      ],
      [
        'key' => 'field_css_problem_text',
        'label' => 'Testo box sinistro',
        'name' => 'cs_problem_text',
        'type' => 'textarea',
        'rows' => 5,
        'new_lines' => 'br',
        'wrapper' => ['width' => '66'],
        'instructions' => 'Testo del box grande a sinistra.',
      ],
      [
        'key' => 'field_css_metric_value',
        'label' => 'Valore numerico finale',
        'name' => 'cs_metric_value',
        'type' => 'text',
        'wrapper' => ['width' => '12'],
        'instructions' => 'Inserisci solo il numero. Per i decimali usa il punto, ad esempio 12.5',
      ],
      [
        'key' => 'field_css_metric_prefix',
        'label' => 'Prefisso',
        'name' => 'cs_metric_prefix',
        'type' => 'text',
        'wrapper' => ['width' => '11'],
        'instructions' => 'Opzionale. Esempi: + oppure €',
      ],
      [
        'key' => 'field_css_metric_suffix',
        'label' => 'Suffisso',
        'name' => 'cs_metric_suffix',
        'type' => 'text',
        'wrapper' => ['width' => '11'],
        'instructions' => 'Opzionale. Esempi: % oppure k',
      ],
      [
        'key' => 'field_css_tab_process',
        'label' => '4–7. Processo e step',
        'type' => 'tab',
        'placement' => 'top',
      ],
      [
        'key' => 'field_css_process_title',
        'label' => 'Titolo principale del processo',
        'name' => 'cs_process_title',
        'type' => 'text',
        'default_value' => 'Come abbiamo risolto.',
        'instructions' => 'Questo titolo viene mostrato come heading principale della parte centrale della pagina.',
      ],
      [
        'key' => 'field_css_process_steps',
        'label' => 'Step del processo',
        'name' => 'cs_process_steps',
        'type' => 'repeater',
        'layout' => 'block',
        'button_label' => 'Aggiungi step',
        'collapsed' => 'field_css_step_title',
        'instructions' => 'Ogni riga corrisponde a uno step. Scegli il modello e compila solo i campi del modello selezionato.',
        'sub_fields' => array_merge([
          [
            'key' => 'field_css_step_layout',
            'label' => 'Modello step',
            'name' => 'layout',
            'type' => 'button_group',
            'choices' => [
              'text_media' => 'Titolo + testo + 1 media',
              'media_grid' => 'Titolo + testo + griglia media',
              'text_only' => 'Titolo + testo',
            ],
            'default_value' => 'text_media',
            'layout' => 'horizontal',
            'instructions' => 'Seleziona il layout desiderato per questo step.',
          ],
          [
            'key' => 'field_css_step_title',
            'label' => 'Titolo step',
            'name' => 'step_title',
            'type' => 'text',
            'instructions' => 'Esempio: Step 1 del processo',
          ],
          [
            'key' => 'field_css_step_text',
            'label' => 'Testo step',
            'name' => 'step_text',
            'type' => 'textarea',
            'rows' => 5,
            'new_lines' => 'br',
            'instructions' => 'Descrizione dello step. Puoi usare anche più paragrafi, lasciando una riga vuota tra uno e l’altro.',
          ],
        ], [
          moma_cs_single_media_group_field('field_css_step_media_single', 'Media step', 'step_media', [
            'instructions' => 'Per questo modello puoi mostrare una sola immagine oppure un video con thumbnail dedicata.',
            'conditional_logic' => [[[
              'field' => 'field_css_step_layout',
              'operator' => '==',
              'value' => 'text_media',
            ]]],
          ]),
          moma_cs_single_media_group_field('field_css_step_grid_primary', 'Media grande a sinistra', 'grid_primary_media', [
            'conditional_logic' => [[[
              'field' => 'field_css_step_layout',
              'operator' => '==',
              'value' => 'media_grid',
            ]]],
          ]),
          moma_cs_single_media_group_field('field_css_step_grid_top_one', 'Media in alto a destra – 1', 'grid_top_one_media', [
            'conditional_logic' => [[[
              'field' => 'field_css_step_layout',
              'operator' => '==',
              'value' => 'media_grid',
            ]]],
          ]),
          moma_cs_single_media_group_field('field_css_step_grid_top_two', 'Media in alto a destra – 2', 'grid_top_two_media', [
            'conditional_logic' => [[[
              'field' => 'field_css_step_layout',
              'operator' => '==',
              'value' => 'media_grid',
            ]]],
          ]),
          moma_cs_single_media_group_field('field_css_step_grid_bottom', 'Media largo in basso', 'grid_bottom_media', [
            'conditional_logic' => [[[
              'field' => 'field_css_step_layout',
              'operator' => '==',
              'value' => 'media_grid',
            ]]],
          ]),
        ]),
      ],
      [
        'key' => 'field_css_tab_tech',
        'label' => '8. Tecnologie / box',
        'type' => 'tab',
        'placement' => 'top',
      ],
      [
        'key' => 'field_css_tech_title',
        'label' => 'Titolo sezione',
        'name' => 'cs_tech_title',
        'type' => 'text',
        'default_value' => 'Tecnologie utilizzate',
      ],
      [
        'key' => 'field_css_tech_text',
        'label' => 'Testo sezione',
        'name' => 'cs_tech_text',
        'type' => 'textarea',
        'rows' => 4,
        'new_lines' => 'br',
      ],
      [
        'key' => 'field_css_tech_mode',
        'label' => 'Contenuto dei box',
        'name' => 'cs_tech_mode',
        'type' => 'button_group',
        'choices' => [
          'media' => '3 box con immagini / video',
          'logos' => '3 box con loghi brand',
        ],
        'default_value' => 'logos',
        'layout' => 'horizontal',
        'instructions' => 'Scegli se mostrare box multimediali oppure loghi con nome del brand.',
      ],
      [
        'key' => 'field_css_tech_media_items',
        'label' => 'Box multimediali',
        'name' => 'cs_tech_media_items',
        'type' => 'repeater',
        'min' => 0,
        'max' => 3,
        'layout' => 'table',
        'button_label' => 'Aggiungi box media',
        'conditional_logic' => [[[
          'field' => 'field_css_tech_mode',
          'operator' => '==',
          'value' => 'media',
        ]]],
        'sub_fields' => [
          [
            'key' => 'field_css_tech_media_label',
            'label' => 'Titolo box (opzionale)',
            'name' => 'label',
            'type' => 'text',
            'instructions' => 'Opzionale. Se vuoto, verrà mostrato solo il contenuto del box.',
          ],
          moma_cs_single_media_group_field('field_css_tech_media_item', 'Contenuto box', 'media_item', [
            'layout' => 'block',
          ]),
        ],
      ],
      [
        'key' => 'field_css_tech_logo_items',
        'label' => 'Box loghi',
        'name' => 'cs_tech_logo_items',
        'type' => 'repeater',
        'min' => 0,
        'max' => 3,
        'layout' => 'table',
        'button_label' => 'Aggiungi box logo',
        'conditional_logic' => [[[
          'field' => 'field_css_tech_mode',
          'operator' => '==',
          'value' => 'logos',
        ]]],
        'sub_fields' => [
          [
            'key' => 'field_css_tech_logo_brand_name',
            'label' => 'Nome brand',
            'name' => 'brand_name',
            'type' => 'text',
            'instructions' => 'Nome mostrato sopra al logo.',
          ],
          [
            'key' => 'field_css_tech_logo_image',
            'label' => 'Logo brand',
            'name' => 'logo_image',
            'type' => 'image',
            'return_format' => 'array',
            'preview_size' => 'medium',
            'instructions' => 'Carica un logo pulito e ben leggibile.',
          ],
        ],
      ],
      [
        'key' => 'field_css_tab_results',
        'label' => '9. Conclusione e numeri',
        'type' => 'tab',
        'placement' => 'top',
      ],
      [
        'key' => 'field_css_results_title',
        'label' => 'Titolo sezione',
        'name' => 'cs_results_title',
        'type' => 'text',
        'default_value' => 'Conclusione',
      ],
      [
        'key' => 'field_css_results_text',
        'label' => 'Testo sezione',
        'name' => 'cs_results_text',
        'type' => 'textarea',
        'rows' => 4,
        'new_lines' => 'br',
      ],
      [
        'key' => 'field_css_results_items',
        'label' => 'Box numerici finali',
        'name' => 'cs_results_items',
        'type' => 'repeater',
        'min' => 0,
        'max' => 3,
        'layout' => 'table',
        'button_label' => 'Aggiungi box numerico',
        'instructions' => 'Ogni box anima il numero al passaggio in viewport.',
        'sub_fields' => [
          [
            'key' => 'field_css_results_item_label',
            'label' => 'Testo sopra il numero',
            'name' => 'label',
            'type' => 'text',
          ],
          [
            'key' => 'field_css_results_item_value',
            'label' => 'Numero finale',
            'name' => 'value',
            'type' => 'text',
            'instructions' => 'Inserisci solo il numero. Esempio: 42 oppure 12.5',
          ],
          [
            'key' => 'field_css_results_item_prefix',
            'label' => 'Prefisso',
            'name' => 'prefix',
            'type' => 'text',
          ],
          [
            'key' => 'field_css_results_item_suffix',
            'label' => 'Suffisso',
            'name' => 'suffix',
            'type' => 'text',
          ],
        ],
      ],
      [
        'key' => 'field_css_tab_video',
        'label' => '10. Video',
        'type' => 'tab',
        'placement' => 'top',
      ],
      moma_cs_single_video_group_field('field_css_feature_video', 'Video principale', 'cs_feature_video', [
        'instructions' => 'Questo blocco genera la card video con play viola e apertura in lightbox.',
      ]),
      [
        'key' => 'field_css_tab_cta',
        'label' => '11. Banner “Vai a vedere il lavoro”',
        'type' => 'tab',
        'placement' => 'top',
      ],
      [
        'key' => 'field_css_work_cta_title',
        'label' => 'Titolo banner',
        'name' => 'cs_work_cta_title',
        'type' => 'text',
        'default_value' => 'Vai a veder il lavoro',
        'wrapper' => ['width' => '40'],
      ],
      [
        'key' => 'field_css_work_cta_button_label',
        'label' => 'Etichetta accessibile pulsante',
        'name' => 'cs_work_cta_button_label',
        'type' => 'text',
        'default_value' => 'Apri il progetto',
        'wrapper' => ['width' => '30'],
        'instructions' => 'Testo usato per aria-label e tooltip del pulsante.',
      ],
      [
        'key' => 'field_css_work_cta_url',
        'label' => 'Link banner',
        'name' => 'cs_work_cta_url',
        'type' => 'url',
        'wrapper' => ['width' => '30'],
        'instructions' => 'Inserisci il link del lavoro pubblicato online o della pagina da aprire.',
      ],
      [
        'key' => 'field_css_tab_related',
        'label' => '12. Progetti correlati',
        'type' => 'tab',
        'placement' => 'top',
      ],
      [
        'key' => 'field_css_related_title',
        'label' => 'Titolo sezione',
        'name' => 'cs_related_title',
        'type' => 'text',
        'default_value' => 'Progetti correlati.',
      ],
      [
        'key' => 'field_css_related_manual',
        'label' => 'Selezione manuale progetti correlati',
        'name' => 'cs_related_manual',
        'type' => 'relationship',
        'post_type' => ['case_study'],
        'filters' => ['search'],
        'min' => 0,
        'max' => 2,
        'return_format' => 'id',
        'instructions' => 'Opzionale. Se lasci vuoto, il tema prova a selezionare automaticamente 2 case studies correlati per categoria.',
      ],
      [
        'key' => 'field_css_tab_contact',
        'label' => '13. Banner contattaci',
        'type' => 'tab',
        'placement' => 'top',
      ],
      [
        'key' => 'field_css_contact_message',
        'label' => 'Nota',
        'name' => '',
        'type' => 'message',
        'message' => 'Il banner finale “Contattaci” riprende automaticamente le impostazioni già presenti nella pagina Servizi. Se non vuoi mostrarlo in frontend, puoi lasciare vuoti i campi del banner Contattaci nelle opzioni della pagina Servizi oppure rimuovere la relativa sezione dal template in futuro.',
      ],
    ],
  ]);

  acf_add_local_field_group([
    'key' => 'group_moma_case_study_single_options',
    'title' => 'Case Studies – Opzioni single',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'location' => [[[
      'param' => 'options_page',
      'operator' => '==',
      'value' => 'moma-case-studies-page',
    ]]],
    'fields' => [
      [
        'key' => 'field_css_opt_tab_single',
        'label' => 'Single case studies',
        'type' => 'tab',
        'placement' => 'top',
      ],
      [
        'key' => 'field_css_opt_single_cursor_enabled',
        'label' => 'Cursore custom sulle immagini e sui video della single',
        'name' => 'csa_single_cursor_enabled',
        'type' => 'true_false',
        'ui' => 1,
        'default_value' => 1,
        'instructions' => 'Questo cursore appare solo sopra immagini e video della pagina dettaglio case study. Non appare sui pulsanti o su altre aree.',
      ],
      [
        'key' => 'field_css_opt_single_cursor_image',
        'label' => 'Immagine cursore single',
        'name' => 'csa_single_cursor_image',
        'type' => 'image',
        'return_format' => 'array',
        'preview_size' => 'medium',
        'conditional_logic' => [[[
          'field' => 'field_css_opt_single_cursor_enabled',
          'operator' => '==',
          'value' => '1',
        ]]],
        'instructions' => 'Usa una sola immagine cursore valida per tutte le single case studies.',
      ],
    ],
  ]);
});
